# Generated by Django 4.2.9 on 2024-01-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('status', models.CharField(default='unread', max_length=10)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.user_reg')),
            ],
        ),
    ]
