# Generated by Django 4.2.9 on 2024-01-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_useractions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likenews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.add_news')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Dislikenews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.add_news')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.user_reg')),
            ],
        ),
    ]
